[project]
name = "owm-worker-weather-categorizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.11.0",
    "outpost-etl-core==0.1.3",
]
