[project]
name = "owm-worker-api-fetch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "outpost-etl-core>=0.1.0",
    "requests>=2.32.5",
]
